"""Central clipboard helper for sensitive copy operations."""

from __future__ import annotations

from PySide6.QtCore import QByteArray, QMimeData, QTimer
from PySide6.QtWidgets import QApplication

_ACTIVE_TIMERS: list[QTimer] = []

_SENSITIVE_MIME_FLAGS: tuple[tuple[str, bytes], ...] = (
    ("x-kde-passwordManagerHint", b"secret"),
    ("application/x-kde-passwordManagerHint", b"secret"),
    ("application/x-qt-windows-mime;value=\"ExcludeClipboardContentFromMonitorProcessing\"", b"1"),
    ("application/x-qt-windows-mime;value=\"CanIncludeInClipboardHistory\"", b"0"),
    ("org.nspasteboard.TransientType", b""),
    ("org.nspasteboard.ConcealedType", b""),
    ("org.nspasteboard.AutoGeneratedType", b""),
)


def sensitive_mime_data(text: str) -> QMimeData:
    """Build clipboard MIME data with best-effort no-history hints."""
    mime = QMimeData()
    mime.setText(text)
    for mime_type, payload in _SENSITIVE_MIME_FLAGS:
        mime.setData(mime_type, QByteArray(payload))
    return mime


def set_sensitive_text(text: str) -> bool:
    if not text:
        return False
    clipboard = QApplication.clipboard()
    if clipboard is None:
        return False
    clipboard.setMimeData(sensitive_mime_data(text))
    return True


def copy_text(text: str, *, clear_after_seconds: int = 60) -> None:
    """Copy text and schedule an independent per-copy clear timer."""
    if not set_sensitive_text(text):
        return
    if clear_after_seconds <= 0:
        return
    snapshot = text
    timer = QTimer()
    timer.setSingleShot(True)
    _ACTIVE_TIMERS.append(timer)

    def _clear() -> None:
        try:
            cb = QApplication.clipboard()
            if cb is not None and cb.text() == snapshot:
                cb.clear()
        finally:
            if timer in _ACTIVE_TIMERS:
                _ACTIVE_TIMERS.remove(timer)
            timer.deleteLater()

    timer.timeout.connect(_clear)
    timer.start(clear_after_seconds * 1000)
